# Generated by Django 3.0.2 on 2020-02-05 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='documents.Document'),
        ),
    ]
